name: galaxeus_ai_dart
description: A sample command-line application.
version: 0.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  ffi: ^2.0.1
  ffmpeg_dart: ^0.0.0
  galaxeus_lib: ^0.0.8
  image: ^3.2.0
  pdf: ^3.8.3
  universal_io: ^2.0.4
  zxing2: ^0.1.1
